spring:
  profiles:
    active: local
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#logging:
#  level:
#    root: debug